#pragma once

#define CONTROLS_MOVE_EAST			GLFW_KEY_D   
#define CONTROLS_MOVE_NORTH			GLFW_KEY_W   
#define CONTROLS_MOVE_WEST			GLFW_KEY_A   
#define CONTROLS_MOVE_SOUTH			GLFW_KEY_S
#define CONTROLS_PICKUP_ITEM		GLFW_KEY_Q
#define CONTROLS_USE_WEAPON			GLFW_KEY_G
#define CONTROLS_USE_EQUIPMENT		GLFW_KEY_E
#define CONTROLS_EXIT				GLFW_KEY_BACKSPACE 
#define CONTROLS_TOGGLE_INVENTORY	GLFW_KEY_TAB
#define CONTROLS_INVENTORY_UP		GLFW_KEY_UP
#define CONTROLS_INVENTORY_DOWN		GLFW_KEY_DOWN
#define CONTROLS_INVENTORY_SELECT   GLFW_KEY_ENTER
#define CONTROLS_INVENTORY_SWITCH   GLFW_KEY_M
#define CONTROLS_TRIGGER_PUNCH		GLFW_KEY_SPACE
#define CONTROLS_START_GAME			GLFW_KEY_ENTER     
#define CONTROLS_RESTART_GAME		GLFW_KEY_ENTER     

// debugging modes:
#define DEBUG_MODE					0
#define SPRITE_MODE					0
#define BAKE_MODE					0
#define EVERYTHING_UNLOCKED			0
#define SOUND_ON					1